[package]
name = "lariv-website-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lariv-website-rs"
path = "src/main.rs"

[dependencies]
lariv-rs = { version = "0.1.0",
	# path = "../../lariv-rs",
	git = "https://github.com/lariv-in/lariv-rs", rev = "c05f9fedeeef7ee218e0ea7a35b072a243cb1533",
	default-features = false, features = [
		"plugin-users",
		"plugin-dashboard",
		"plugin-filesystem",
		"plugin-website",
		"plugin-blog",
] }
tokio = { version = "1", features = ["full"] }
anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
frunk = { version = "0.5.0", features = ["serde", "std"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
chrono = "0.4"
sea-orm = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres", "sqlx-sqlite"] }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }

[profile.release]
lto = "thin"
strip = true
codegen-units = 1
